### ISSUE TITLE
Subscribing to events throws NotSupportedException

### ISSUE THREAD

**Issue by adrianoc** [adrianoc/cecilifier#127]
Error
---
System.NotSupportedException: Assignment to proc.Exited (AddAssignmentExpression) is not supported.
   at Cecilifier.Core.AST.ExpressionVisitor.ProcessMethodReference(SimpleNameSyntax node, IMethodSymbol method) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 1080
   at Cecilifier.Core.AST.ExpressionVisitor.HandleIdentifier(SimpleNameSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 1267
   at Cecilifier.Core.AST.ExpressionVisitor.VisitIdentifierName(IdentifierNameSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 394
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.ExpressionVisitor.VisitAssignmentExpression(AssignmentExpressionSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 268
   at Microsoft.CodeAnalysis.CSharp.Syntax.AssignmentExpressionSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Cecilifier.Core.AST.ExpressionVisitor.VisitArrowExpressionClause(ArrowExpressionClauseSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 143
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.ExpressionVisitor.Visit(IVisitorContext ctx, String ilVar, SyntaxNode node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 130
   at Cecilifier.Core.AST.MethodDeclarationVisitor.VisitArrowExpressionClause(ArrowExpressionClauseSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 52
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Cecilifier.Core.AST.MethodDeclarationVisitor.<>n__1(MethodDeclarationSyntax node)
   at Cecilifier.Core.AST.MethodDeclarationVisitor.<>c__DisplayClass5_0.<VisitMethodDeclaration>b__0(String _) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 74
   at Cecilifier.Core.AST.SyntaxWalkerBase.WithCurrentMethod(String declaringTypeName, String localVariable, String methodName, String[] paramTypes, Action`1 action) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/SyntaxWalkerBase.cs:line 146
   at Cecilifier.Core.AST.MethodDeclarationVisitor.ProcessMethodDeclarationInternal(SyntaxNode node, String declaringTypeName, String variableName, IMethodSymbol methodSymbol, SyntaxTokenList modifiers, String simpleName, String methodName, Boolean refReturn, Action`1 runWithCurrent, SyntaxList`1 attributes, SeparatedSyntaxList`1 parameters, IList`1 typeParameters) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 156
   at Cecilifier.Core.AST.MethodDeclarationVisitor.ProcessMethodDeclaration[T](T node, String variableName, String simpleName, String fqName, Boolean refReturn, Action`1 runWithCurrent, IList`1 typeParameters) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 186
   at Cecilifier.Core.AST.MethodDeclarationVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 68
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.TypeDeclarationVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/TypeDeclarationVisitor.cs:line 78
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Cecilifier.Core.AST.TypeDeclarationVisitor.VisitClassDeclaration(ClassDeclarationSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/TypeDeclarationVisitor.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.CompilationUnitVisitor.VisitClassDeclaration(ClassDeclarationSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/CompilationUnitVisitor.cs:line 64
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
   at Cecilifier.Core.AST.CompilationUnitVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/AST/CompilationUnitVisitor.cs:line 24
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.Cecilifier.Run(Stream content, CecilifierOptions options) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Core/Cecilifier.cs:line 50
   at Cecilifier.Web.Startup.<Configure>g__CecilifyCodeAsync|6_2(WebSocket webSocket) in /home/adriano/Development/Adriano/study/DotNet/Cecilifier/Cecilifier.Web/Startup.cs:line 137

Associated snippet:
----
```CSharp
using System;
using System.Diagnostics;

class Foo 
{
	private void Handler(object sender, EventArgs args) { } 

	void SetEvent(Process proc) => proc.Exited  += Handler;
}
```

**Comment by adrianoc** [comment]
Of course the syntax in the example is not valid. I'll double check

- [ ] Why I did not got a compiler error ? (or did I, and it was ignored ?)
- [ ] Ensure that subscribing to event is working

**Comment by adrianoc** [comment]
This issue depends on #130
