### ISSUE TITLE
Forward field assignment generates invalid code missing field reference

### ISSUE THREAD

**Issue by icnocop** [adrianoc/cecilifier#182]
Hi.

Thank you for cecilifier.

Trying to cecilify the following code:
```
public struct MyStruct
{
	public MyStruct()
	{
		myField = new ushort[42];
	}

	public ushort[] myField;
}
```

Produces the following code:
```
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;
using System; 
using System.IO;
using System.Linq;
using BindingFlags = System.Reflection.BindingFlags;
using Cecilifier.Runtime;
               
public class SnippetRunner
{
	public static void Main(string[] args)
	{
        // setup a `reflection importer` to ensure references to System.Private.CoreLib are replaced with references to `netstandard`. 
        var mp = new ModuleParameters { Architecture = TargetArchitecture.AMD64, Kind =  ModuleKind.Dll, ReflectionImporterProvider = new SystemPrivateCoreLibFixerReflectionProvider() };
		using(var assembly = AssemblyDefinition.CreateAssembly(new AssemblyNameDefinition("Cecilified", Version.Parse("1.0.0.0")), Path.GetFileName(args[0]), mp))
        {

			//StructDeclaration : MyStruct
			var st_MyStruct_0 = new TypeDefinition("", "MyStruct", TypeAttributes.SequentialLayout | TypeAttributes.Sealed |TypeAttributes.AnsiClass | TypeAttributes.BeforeFieldInit | TypeAttributes.Public, assembly.MainModule.ImportReference(typeof(System.ValueType)));
			assembly.MainModule.Types.Add(st_MyStruct_0);
			

			//Method : .ctor
			var ctor_MyStruct_1 = new MethodDefinition(".ctor", MethodAttributes.Public| MethodAttributes.RTSpecialName | MethodAttributes.SpecialName | MethodAttributes.HideBySig, assembly.MainModule.TypeSystem.Void);
			st_MyStruct_0.Methods.Add(ctor_MyStruct_1);
			ctor_MyStruct_1.Body.InitLocals = true;
			var il_ctor_2 = ctor_MyStruct_1.Body.GetILProcessor();

			//myField = new ushort[42];
			var Ldarg_0_3 = il_ctor_2.Create(OpCodes.Ldarg_0);
			il_ctor_2.Append(Ldarg_0_3);
			il_ctor_2.Emit(OpCodes.Ldc_I4, 42);
			il_ctor_2.Emit(OpCodes.Newarr, assembly.MainModule.TypeSystem.UInt16);
			il_ctor_2.Emit(OpCodes.Stfld);
			il_ctor_2.Emit(OpCodes.Ret);
			var fld_myField_4 = new FieldDefinition("myField", FieldAttributes.Public, assembly.MainModule.TypeSystem.UInt16.MakeArrayType());
			st_MyStruct_0.Fields.Add(fld_myField_4);

		    assembly.Write(args[0]);
        }
	}
}
```

However, the following exception occurs during runtime at `il_ctor_2.Emit(OpCodes.Stfld);`:
```
System.ArgumentException
  HResult=0x80070057
  Message=opcode
  Source=Mono.Cecil
  StackTrace:
   at Mono.Cecil.Cil.Instruction.Create(OpCode opcode)
   at Mono.Cecil.Cil.ILProcessor.Create(OpCode opcode)
   at Mono.Cecil.Cil.ILProcessor.Emit(OpCode opcode)
   at SnippetRunner.Main(String[] args) in C:\Users\rami.abughazaleh\Downloads\Cecilified\Program.cs:line 35
```

Any ideas?

Thank you.

**Comment by adrianoc** [comment]
Hi.

There's a bug when processing forwarded fields (I'd bet that any forwarded member, beside methods, will have a similar problem) which leads **Cecilifier** to emit the code:

> il_ctor_2.Emit(OpCodes.Stfld);

which is missing the target  `field reference` (i.e, the field to store the value to).

You can see that just a few lines below the field is being created:

```CSharp
var fld_myField_4 = new FieldDefinition("myField", FieldAttributes.Public, assembly.MainModule.TypeSystem.UInt16.MakeArrayType());
st_MyStruct_0.Fields.Add(fld_myField_4);
```

There are 2 workarounds you can use here:

1. Declare the field before accessing it:
 
```CSharp
public struct MyStruct
{
	public ushort[] myField;

	public MyStruct()
	{
		myField = new ushort[42];
	}
}
```
2. Manually changing the _cecilified code_ to something like:

```CSharp
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;
using System; 
using System.IO;
using System.Linq;
using BindingFlags = System.Reflection.BindingFlags;
using Cecilifier.Runtime;
               
public class SnippetRunner
{
    public static void Main(string[] args)
    {
        // setup a `reflection importer` to ensure references to System.Private.CoreLib are replaced with references to `netstandard`. 
        var mp = new ModuleParameters { Architecture = TargetArchitecture.AMD64, Kind =  ModuleKind.Dll, ReflectionImporterProvider = new SystemPrivateCoreLibFixerReflectionProvider() };
        using(var assembly = AssemblyDefinition.CreateAssembly(new AssemblyNameDefinition("Cecilified", Version.Parse("1.0.0.0")), Path.GetFileName(args[0]), mp))
        {

            //StructDeclaration : MyStruct
            var st_MyStruct_0 = new TypeDefinition("", "MyStruct", TypeAttributes.SequentialLayout | TypeAttributes.Sealed |TypeAttributes.AnsiClass | TypeAttributes.BeforeFieldInit | TypeAttributes.Public, assembly.MainModule.ImportReference(typeof(System.ValueType)));
            assembly.MainModule.Types.Add(st_MyStruct_0);
			
            //Method : .ctor
            var ctor_MyStruct_1 = new MethodDefinition(".ctor", MethodAttributes.Public| MethodAttributes.RTSpecialName | MethodAttributes.SpecialName | MethodAttributes.HideBySig, assembly.MainModule.TypeSystem.Void);
            st_MyStruct_0.Methods.Add(ctor_MyStruct_1);
            ctor_MyStruct_1.Body.InitLocals = true;
            var il_ctor_2 = ctor_MyStruct_1.Body.GetILProcessor();

            // Moved field creation to here.
            var fld_myField_4 = new FieldDefinition("myField", FieldAttributes.Public, assembly.MainModule.TypeSystem.UInt16.MakeArrayType());
            st_MyStruct_0.Fields.Add(fld_myField_4);

            //myField = new ushort[42];
            var Ldarg_0_3 = il_ctor_2.Create(OpCodes.Ldarg_0);
            il_ctor_2.Append(Ldarg_0_3);
            il_ctor_2.Emit(OpCodes.Ldc_I4, 42);
            il_ctor_2.Emit(OpCodes.Newarr, assembly.MainModule.TypeSystem.UInt16);

            //il_ctor_2.Emit(OpCodes.Stfld);
            il_ctor_2.Emit(OpCodes.Stfld, fld_myField_4);

            il_ctor_2.Emit(OpCodes.Ret);
            //var fld_myField_4 = new FieldDefinition("myField", FieldAttributes.Public, assembly.MainModule.TypeSystem.UInt16.MakeArrayType());
            //st_MyStruct_0.Fields.Add(fld_myField_4);

            assembly.Write(args[0]);
        }
     }
}
```
