### ISSUE TITLE
Break statement outside a switch statement throws exception

### ISSUE THREAD

**Issue by tnechepurencko** [adrianoc/cecilifier#232]
Error
---
System.InvalidOperationException: Invalid break.
   at Cecilifier.Core.AST.StatementVisitor.VisitBreakStatement(BreakStatementSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 133
   at Microsoft.CodeAnalysis.CSharp.Syntax.BreakStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.StatementVisitor.Visit(SyntaxNode node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Cecilifier.Core.AST.StatementVisitor.VisitForStatement(ForStatementSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 57
   at Microsoft.CodeAnalysis.CSharp.Syntax.ForStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.StatementVisitor.Visit(SyntaxNode node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Cecilifier.Core.AST.StatementVisitor.Visit(IVisitorContext context, String ilVar, CSharpSyntaxNode node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 26
   at Cecilifier.Core.AST.MethodDeclarationVisitor.VisitBlock(BlockSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 57
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Cecilifier.Core.AST.MethodDeclarationVisitor.<>n__1(MethodDeclarationSyntax node)
   at Cecilifier.Core.AST.MethodDeclarationVisitor.<>c__DisplayClass5_0.<VisitMethodDeclaration>b__0(String _) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 70
   at Cecilifier.Core.AST.SyntaxWalkerBase.WithCurrentMethod(String declaringTypeName, String localVariable, String methodName, String[] paramTypes, Action`1 action) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/SyntaxWalkerBase.cs:line 289
   at Cecilifier.Core.AST.MethodDeclarationVisitor.ProcessMethodDeclarationInternal(SyntaxNode node, String declaringTypeName, String variableName, IMethodSymbol methodSymbol, SyntaxTokenList modifiersTokens, String simpleName, String methodName, Boolean refReturn, Action`1 runWithCurrent, SyntaxList`1 attributes, SeparatedSyntaxList`1 parameters, IList`1 typeParameters) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 166
   at Cecilifier.Core.AST.MethodDeclarationVisitor.ProcessMethodDeclaration[T](T node, String variableName, String simpleName, String fqName, Boolean refReturn, Action`1 runWithCurrent, IList`1 typeParameters) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 196
   at Cecilifier.Core.AST.MethodDeclarationVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/MethodDeclarationVisitor.cs:line 64
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.TypeDeclarationVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/TypeDeclarationVisitor.cs:line 92
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Cecilifier.Core.AST.TypeDeclarationVisitor.VisitClassDeclaration(ClassDeclarationSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/TypeDeclarationVisitor.cs:line 41
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.AST.CompilationUnitVisitor.VisitDeclaredTypesSortedByDependencies() in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/CompilationUnitVisitor.cs:line 54
   at Cecilifier.Core.AST.CompilationUnitVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/CompilationUnitVisitor.cs:line 22
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.Cecilifier.Process(Stream content, CecilifierOptions options) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/Cecilifier.cs:line 48
   at Cecilifier.Web.Startup.ProcessWebSocketAsync(WebSocket webSocket, Byte[] buffer) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Web/Startup.cs:line 174
   at Cecilifier.Web.Startup.ProcessWebSocketAsync(WebSocket webSocket, Byte[] buffer) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Web/Startup.cs:line 204

Associated snippet:
----
```CSharp
// Supported CSharp language version: 11 https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11
using System;
class Foo
{
	struct Person
	{
		public string name;
		public int age;
	}
	public static void Main(string[] args) {
		var x = 0;
		for(int i = 0; i > -1; i  ) {
			x  = 1;
			break;
		}
	}
}
```

**Comment by adrianoc** [comment]
The [issue](https://github.com/adrianoc/cecilifier/blob/main/Cecilifier.Core/AST/StatementVisitor.cs#L133) happens because cecilifier is assuming that a `break` can only appear inside a `switch` statement (which is of course, wrong).

Some more tests to add.

```C#
class Foo
{
    public void M(int n) 
    {
	for(int i = 0; i < 2; i++  ) 
        {
            System.Console.WriteLine("1. Before break");
            break;
            System.Console.WriteLine("1. After break");
	}
        
        while (n++ != 1)
            break;
        
        foreach(var c in n.ToString())
        {
            if (n != 10)
            {
                System.Console.WriteLine("2. Before break");
                break;
                System.Console.WriteLine("2. After break");
            }
            else
                break;
        }
   }
}
```

**Comment by adrianoc** [comment]
Thanks @tnechepurencko for reporting
