### ISSUE TITLE
Exception is thrown if code contains references to fields of generic types

### ISSUE THREAD

**Issue by adrianoc** [adrianoc/cecilifier#310]
Error
---
System.Exception: Could not resolve reference to field: field
   at Cecilifier.Core.Extensions.ISymbolExtensions.EnsureFieldExists(IFieldSymbol fieldSymbol, IVisitorContext context, SimpleNameSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/Extensions/ISymbolExtensions.cs:line 138
   at Cecilifier.Core.AST.SyntaxWalkerBase.ProcessField(String ilVar, SimpleNameSyntax node, IFieldSymbol fieldSymbol) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/SyntaxWalkerBase.cs:line 436
   at Cecilifier.Core.AST.ExpressionVisitor.HandleIdentifier(SimpleNameSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 1464
   at Cecilifier.Core.AST.ExpressionVisitor.VisitMemberAccessExpression(MemberAccessExpressionSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 912
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitEqualsValueClause(EqualsValueClauseSyntax node)
   at Cecilifier.Core.AST.ExpressionVisitor.VisitEqualsValueClause(EqualsValueClauseSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 306
   at Microsoft.CodeAnalysis.CSharp.Syntax.EqualsValueClauseSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Cecilifier.Core.AST.ExpressionVisitor.Visit(IVisitorContext ctx, String ilVar, SyntaxNode node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/ExpressionVisitor.cs:line 147
   at Cecilifier.Core.AST.StatementVisitor.ProcessVariableInitialization(VariableDeclaratorSyntax localVar, ITypeSymbol variableType) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 322
   at Cecilifier.Core.AST.StatementVisitor.HandleVariableDeclaration(VariableDeclarationSyntax declaration) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 345
   at Cecilifier.Core.AST.StatementVisitor.VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 220
   at Cecilifier.Core.AST.StatementVisitor.Visit(SyntaxNode node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/StatementVisitor.cs:line 37
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitGlobalStatement(GlobalStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.GlobalStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Cecilifier.Core.AST.GlobalStatementHandler.HandleGlobalStatement(GlobalStatementSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/GlobalStatementHandler.cs:line 86
   at Cecilifier.Core.AST.CompilationUnitVisitor.VisitGlobalStatement(GlobalStatementSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/CompilationUnitVisitor.cs:line 36
   at Microsoft.CodeAnalysis.CSharp.Syntax.GlobalStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
   at Cecilifier.Core.AST.CompilationUnitVisitor.VisitCompilationUnit(CompilationUnitSyntax node) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/AST/CompilationUnitVisitor.cs:line 24
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
   at Cecilifier.Core.Cecilifier.Process(Stream content, CecilifierOptions options) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Core/Cecilifier.cs:line 49
   at Cecilifier.Web.Startup.ProcessWebSocketAsync(WebSocket webSocket, Int32 remoteIpAddressHashCode, Byte[] buffer) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Web/Startup.cs:line 212
   at Cecilifier.Web.Startup.ProcessWebSocketAsync(WebSocket webSocket, Int32 remoteIpAddressHashCode, Byte[] buffer) in /home/adriano/Projects/study/DotNet/Cecilifier/Cecilifier.Web/Startup.cs:line 244

Associated snippet:
----
```CSharp

**Comment by adrianoc** [comment]
already fixed by 9934ca0bded74fb6f1ec8c6021002811930ed023
